// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr7cxLUiTPhEHCX4Tf04JoEV66fDIq0lw',
    appId: '1:169027711687:web:d000f6ba3b654cba5e84e2',
    messagingSenderId: '169027711687',
    projectId: 'intento-chat-c5a63',
    authDomain: 'intento-chat-c5a63.firebaseapp.com',
    storageBucket: 'intento-chat-c5a63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChD1ByuFkNzDlKz_EQCU8ZHkdLhnmT5aE',
    appId: '1:169027711687:android:cf43cfab495cc2885e84e2',
    messagingSenderId: '169027711687',
    projectId: 'intento-chat-c5a63',
    storageBucket: 'intento-chat-c5a63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr8m5yiXUxXFRPsS-TRf2VG80TK4FaTt4',
    appId: '1:169027711687:ios:88e3f47435416b205e84e2',
    messagingSenderId: '169027711687',
    projectId: 'intento-chat-c5a63',
    storageBucket: 'intento-chat-c5a63.appspot.com',
    iosBundleId: 'com.example.intentofirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr8m5yiXUxXFRPsS-TRf2VG80TK4FaTt4',
    appId: '1:169027711687:ios:88e3f47435416b205e84e2',
    messagingSenderId: '169027711687',
    projectId: 'intento-chat-c5a63',
    storageBucket: 'intento-chat-c5a63.appspot.com',
    iosBundleId: 'com.example.intentofirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr7cxLUiTPhEHCX4Tf04JoEV66fDIq0lw',
    appId: '1:169027711687:web:009a96eedc332f9f5e84e2',
    messagingSenderId: '169027711687',
    projectId: 'intento-chat-c5a63',
    authDomain: 'intento-chat-c5a63.firebaseapp.com',
    storageBucket: 'intento-chat-c5a63.appspot.com',
  );
}
